---

- hosts: all
  become: true
  tasks:

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"    

  - name: install mariadb and samba package
    apt:
      name: 
        - mariadb-server
        - samba  
      state: latest
    when: ansible_distribution == "Ubuntu"    

  - name: install apache2 and php package
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest  

#     when: ansible_distribution == "Ubuntu" - daca celelalte servere nu folosesc Ubuntu sau orice alt OS care foloseste "apt" ca si pakage manager"
#     when: ansible_distribution in ["Debian", "Ubuntu"] - daca celelalte servere nu folosesc Ubuntu sau orice alt OS care foloseste "apt" ca si pakage manager, se va instala doar pe serverele ce rleaza cu Ubuntu si/sau Debian"


#when we have diferent servers from diferit groups and pourposes: ex: [main_server] [web_servers] ... etc
#-hosts: web_servers        
# become: true
# tasks:
# exemplu
#- name: install apache2 and php package
#    apt:
#      name:
#        - apache2
#        - libapache2-mod-php  
#      state: latest
#      update_cache: yes  
#     when: ansible_distribution == "Ubuntu" - daca celelalte servere nu folosesc Ubuntu sau orice alt OS care foloseste "apt" ca si pakage manager"
#     when: ansible_distribution in ["Debian", "Ubuntu"] - daca celelalte servere nu folosesc Ubuntu sau orice alt OS care foloseste "apt" ca si pakage manager, se va instala doar pe serverele ce rleaza cu Ubuntu si/sau Debian"   
